server:
    port: 9401
spring:
  profiles:
      active: dev
  application:
      name: mall-auth
  cloud:
    nacos:
      discovery:
          server-addr: http://1.116.200.39:8848
  jackson:
      date-format: yyyy-MM-dd HH:mm:ss
  redis:
      database: 0
      port: 6379
      host: 39.108.149.230
      password: 
management:
  endpoints:
    web:
      exposure:
          include: "*"