server:
    port: 10001
spring:
  redis:
    host: 39.108.149.230
    database: 0
    port: 6379
    password: CPC@2021
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://106.12.2.202:3306/mall?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: mall
    password: pa2sw0rd
  application:
    name: mall-auth

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml